version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tpachat
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  tpachat:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    image: gacharsadok1/achat
    container_name: tpachat-container
    restart: on-failure
    ports:
      - "8089:8089"
    networks:
      - bored-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachat?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/var/lib/tpachat
    stdin_open: true
    tty: true
networks:
  bored-network:
    name: bored-network
volumes:
  db:
  .m2:
